import cv2
camera = cv2.VideoCapture(0)
ret, img = camera.read()
cv2.imwrite('Screenshot.jpeg', img)
camera.release()
img = cv2.imread('Screenshot.jpeg')
img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
img = cv2.cvtColor(img, cv2.COLOR_GRAY2BGR)
cv2.line(img, (0, 0), (img.shape[1], img.shape[0]) , (0,0,255), 5)
cv2.rectangle(img, (100, 200), (300, 400), (0, 255, 0), 5)
cv2.imwrite('Screenshot.jpeg', img)
cv2.imshow('Screenshot', img)
cv2.waitKey(0)
cv2.destroyAllWindows()